### ISSUE TITLE
CS course prerequisite diagram

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#105]
Integrate a course prerequisite diagram to our webpage (probably by embedding it as an iframe). There are actually a few different implementations of this already available, including [@AnimeAllstar's ](https://github.com/AnimeAllstar/UBSee) personal project. We should research different options first.

**Comment by AnimeAllstar** [comment]
https://www.ubsee.dev/subject/CPSC

**Comment by eqfy** [comment]
We can also use the department's prerequisites:
https://www.cs.ubc.ca/prerequisite-rules
