### ISSUE TITLE
Remove Google analytics 

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#110]
Investigate Google analytics. Maybe ask Tiger Oaks.
We probably only need the page view data.

**Comment by AnimeAllstar** [comment]
If you check [config.yml](https://github.com/ubccsss/ubccsss.org/blob/master/config.yml), you'll notice that google analytics has been set up?

The tracking id is `UA-88004303-1` [(line 5)](https://github.com/ubccsss/ubccsss.org/blob/master/config.yml#L5)

I think we might need to ask one of the older maintainers to see if they have it set up on their own account?

**Comment by eqfy** [comment]
We discovered that CloudFlare Web Analytics achieves the functionalities that we wanted to have. Hence, due to privacy concerns, we should remove Google Analytics from our website.
