### ISSUE TITLE
Custom layout not applying to posts

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#124]
It seems that for newly created posts (not events), we use the default Bootstrap layout instead of our [custom layout](https://github.com/ubccsss/ubccsss.org/blob/ceab27548d9ddd03c8476da283b8da779463f223/layouts/events/content.html#L6-L8). Investigate why this is happening.

**Comment by kewbish** [comment]
Some initial testing:

`hugo new posts/2022-01-01-cool-event.md` creates a new post. It seems to be using our layout fine?

The custom layout you highlighted includes a section for tags and categories - these aren't present on posts by default, but I found that if you include a `tags: ["career"]` in the YAML header, a tags button will show up. Same for categories.

(We could make this tag section show up by default in the YAML header, this would just involve creating an `archetypes/post.md` similar to the `archetypes/event.md`. I think the two template files for events + posts are the same already as well.)

**Comment by kewbish** [comment]
Notes from meeting: 
- We had custom Hugo template overrides for our `event` content type - this can be fixed by copying over the partial.
- We also had custom archetype for `event` posts that wasn't applied to `posts` - this can also be fixed by copying over the archetype.
