### ISSUE TITLE
Fix about section navigation

### ISSUE THREAD

**Issue by NotWoods** [ubccsss/ubccsss.org#13]
On https://ubccsss.org/about/team/2018/, one of the links at the bottom should go to the 2017-18 exec team page. Currently the only links go up and to the end of the next section (Miscellaneous).

---

![InkedScreenshot_2019-04-14 Core Executives—2018–2019_LI](https://user-images.githubusercontent.com/1782266/56100766-95729100-5ed1-11e9-8ded-547976a349e6.jpg)

**The link circled in red should go to the Core Executives 2017-2018 page**

**Comment by AmirNaghibi** [comment]
I'll investigate this on Saturday.

**Comment by NotWoods** [comment]
The "Outline" works fine, this issue is concerned with the links beside it.

**Comment by AmirNaghibi** [comment]
@NotWoods 
I see. So should I change the link from
**Volunteering Committee** to **Core Executive--2017-2018 **?
basically, the link circled red will point to previous execs and the link underlined blue will point to next year exec for each page.

**Comment by NotWoods** [comment]
@AmirNaghibi Yes, that's the intended behaviour
