### ISSUE TITLE
Remove the extra hop between Cloudflare's CDN and Netlify's CDN

### ISSUE THREAD

**Issue by RamitKataria** [ubccsss/ubccsss.org#179]
Currently, the website is proxied through Cloudflare's DNS even though it is already hosted on a CDN by Netlify which runs on Google's and Amazon's CDNs. [Here's an article](https://answers.netlify.com/t/support-guide-why-not-proxy-to-netlify/8869) from Netlify support about why we shouldn't use 2 CDNs. The main benefit to us is removing an extra hop and being able to clear cache directly through Netlify in case something breaks and we need to rollback or quickly fix something.

To keep Cloudflare Analytics working, we need to use manual setup since Cloudflare will not be able to add the script element itself anymore, before turning off the proxy.

**Comment by eqfy** [comment]
That's an interesting read, thanks for bringing this up @RamitKataria! I guess we will be removing the cloudflare proxy then.

**Comment by RamitKataria** [comment]
Looks like I forgot to update the submodule version
