### ISSUE TITLE
Netlify should auto build and deploy changes made to https://github.com/ubccsss/hugo-bootstrap-5

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#181]

**Comment by AnimeAllstar** [comment]
I doubt this is possible. I suggest continuing to make changes in this repo. Making changes to [hugo-bootstrap-5](https://github.com/ubccsss/hugo-bootstrap-5) and constantly updating the submodule is a pain since renders don't work.

**Comment by AnimeAllstar** [comment]
That is a nice idea, let's axe the submodule and use it as a static repo.

**Comment by AnimeAllstar** [comment]
I found an example where the submodule is updated: https://flaviocopes.com/netlify-deploy-git-submodule-github-actions/

But I think the static option is better. This will complicate stuff.

**Comment by kewbish** [comment]
I'll take on moving it all into the ubccsss.org repo sometime later this week then, pending no further disagreement.
