### ISSUE TITLE
Fix course reviews database for "Topics in Computer Science" courses

### ISSUE THREAD

**Issue by AnimeAllstar** [ubccsss/ubccsss.org#218]
Current ssc:
![image](https://user-images.githubusercontent.com/39626451/187810810-7de45d34-bcb2-4a86-92b8-044da5d9a582.png)

Current ubccsss.org
![image](https://user-images.githubusercontent.com/39626451/187810859-684cb2fa-daab-479f-83e3-e12e9fb3bb02.png)

Also, check for other issues with incorrect cs courses. Maybe we should remove "Topics in Computer Science" courses since they are essentially trial offerings.

**Comment by AnimeAllstar** [comment]
I'm blind. I misread.

**Comment by kewbish** [comment]
Haha sorry! I was too lazy to make a new page for every 436 course since none of them had reviews anyways :upside_down_face:
