### ISSUE TITLE
Add validation checks for Difficulty and Overall Course Quality

### ISSUE THREAD

**Issue by AnimeAllstar** [ubccsss/ubccsss.org#243]
Should we make `Difficulty` and `Overall Course Quality` required fields, and add validation to ensure that they have been set manually?

I made https://github.com/ubccsss/ubccsss.org/issues/242 as a test and was able to submit it without entering anything.

Lemme know what you'll think.

**Comment by kewbish** [comment]
I think we can go ahead and make them required (makes the worker code less )

Side note: I thought I handled the case where the difficulty wasn't set manually

**Comment by AnimeAllstar** [comment]
Could we at least display the default values to show the user what the default value is?
