### ISSUE TITLE
Newsletter signup from website

### ISSUE THREAD

**Issue by shubhbhalla** [ubccsss/ubccsss.org#246]
Have a way for people to signup to our newsletter from our website! The newsletter signup link is located here - http://eepurl.com/h-QQ_z

**Comment by AnimeAllstar** [comment]
I'll add a popup that gets disabled after the user closes it (using a cookie) when the user initially visits the site. Besides that I'll add a spot next to the discord link for a permanent link.

**Comment by shubhbhalla** [comment]
Thanks boss
