### ISSUE TITLE
Can we have a description for every course that we have in course reviews?

### ISSUE THREAD

**Issue by shubhbhalla** [ubccsss/ubccsss.org#248]
All courses in the course reviews page do not have a description. Can we copy the description from SSC and put it on our website when a person goes to rate the courses?

<img width="1060" alt="Screen Shot 2022-09-24 at 3 23 12 PM" src="https://user-images.githubusercontent.com/67706402/192120714-c76af896-efa1-4ea4-b24f-7238fdb18bb6.png">
No course description ^

<img width="1240" alt="Screen Shot 2022-09-24 at 3 27 43 PM" src="https://user-images.githubusercontent.com/67706402/192120758-d960df33-1e34-4076-bcaf-909f33ad2333.png">
What we can take from SSC ^

**Comment by AnimeAllstar** [comment]
@kewbish We could consider using one of these to get the data from an API: 
- https://github.com/StuffByLiang/realtime-ubc-courses-api
- https://ubcexplorer.io/api

I'm not sure if they're up to date though. Maybe it's better to hardcode it then.

**Comment by AnimeAllstar** [comment]
I have made a feature request to ubcgrades to add course info since we're already calling their API for course grades https://github.com/DonneyF/ubcgrades/issues/6.

**Comment by kewbish** [comment]
Sounds good, thank you! In the meantime I think hard coding is acceptable, course descriptions usually don't change too much + there'll be some edge cases because some upper-level courses don't have descriptions..
