### ISSUE TITLE
CS Clubs unified events listing webste

### ISSUE THREAD

**Issue by rayhua12** [ubccsss/ubccsss.org#255]
- On existing clubs page, add a unified calendar.
- On existing clubs page, expand out engagement channel links.

**Comment by AnimeAllstar** [comment]
Is `unified calendar` just the calendar?

What does `expand out engagement channel links` mean?

**Comment by kewbish** [comment]
(Ray and I briefly chatted about ^ IRL) From what I understand:
- unified calendar is another version of the calendar we have on the homepage, but with other clubs' events on it. We'd need to fetch ICS files for other clubs' calendars (if they even exist), or we could just wait until they contact us with something to put up.
- expand out engagement channel links is adding some more information like club registration, club about, club events, club social links to each club entry.

I'll work on adding a popover to each club card with some more information, not sure how to approach the calendar seeing as it'll involve getting other clubs' events and not all of them will have consistent event calendar formats. Thoughts?

**Comment by argonaut0** [comment]
Can someone write a step-by-step documentation on how to add a .ics file from popular calendars, say for example google calendar and outlook? I think this would be required before we consider this issue complete.

**Comment by kewbish** [comment]
Closing as per #274 #260 #261.
