### ISSUE TITLE
Wrap user input for reviews

### ISSUE THREAD

**Issue by AnimeAllstar** [ubccsss/ubccsss.org#300]
<img width="977" alt="Screenshot 2022-11-02 at 11 08 29 PM" src="https://user-images.githubusercontent.com/39626451/199657650-e5265129-54c6-4aa0-bcb5-12fede70dee0.png">

**Comment by kewbish** [comment]
I think this only happens because you submitted a review with one super long word and we didn't account for sub-word breaking.

Regardless, `word-wrap: break-word;` should fix it!
