### ISSUE TITLE
increase font size

### ISSUE THREAD

**Issue by shubhbhalla** [ubccsss/ubccsss.org#319]
Increase the font size and make it more obvious that the text is for the course description .

![Screen Shot 2022-11-17 at 6 32 06 PM](https://user-images.githubusercontent.com/67706402/202603444-320363f2-eddd-494b-b14f-713b2ef2534b.png)

**Comment by kewbish** [comment]
For consistency, I don't think we should increase the font size. Would something like this look better?

![image](https://user-images.githubusercontent.com/45278276/202745118-89e647c8-e147-49be-a497-2e40b574fb4e.png)

**Comment by shubhbhalla** [comment]
Yes looks great!
