### ISSUE TITLE
Prettifying the codebase

### ISSUE THREAD

**Issue by AnimeAllstar** [ubccsss/ubccsss.org#324]
The codebase is filled with inconsistent code styles which results in large diffs for small changes. This is unideal because it distracts from actual changes being made in PRs and is ugly and hard to look at. I suggest that we try and complete the following tasks for this issue:

- [ ] Find a way to specify formatting for the Hugo codebase ([prettier](https://discourse.gohugo.io/t/hugo-and-prettier/22596/3) or something else)
- [ ] Update DOCS to specify how the user can format their code before making PRs
- [ ] Create a GitHub Action that formats PRs or blocks them using a failed test (in case the PR owner doesn't format their code)
- [ ] Reformat all code in the codebase

**Comment by kewbish** [comment]
I strongly agree - I think the main thing is standardising Prettier configs as everyone seems to be using different formatters / different local preferences. Is anyone opposed to just using default Prettier config + the Go plugin that you linked?
