### ISSUE TITLE
Calendar down

### ISSUE THREAD

**Issue by AnimeAllstar** [ubccsss/ubccsss.org#325]
@argonaut0 do you have access to this?
<img width="1624" alt="Screenshot 2022-12-04 at 6 11 55 AM" src="https://user-images.githubusercontent.com/39626451/205495463-d2c33846-c7d0-41fe-b8c5-ddec271b7529.png">

I think the issue is related to Heroku shutting down their free plan starting November 28.

**Comment by kewbish** [comment]
:laughing: 

IIRC we weren't the ones who developed this - we were using [this repo](https://github.com/niccokunzmann/open-web-calendar) as far as I know. I put up a PR to change the hosting URL.
