### ISSUE TITLE
Calendar is not loading

### ISSUE THREAD

**Issue by shubhbhalla** [ubccsss/ubccsss.org#344]
The calendar is not loading

<img width="1056" alt="Screenshot 2023-01-06 at 12 13 55 PM" src="https://user-images.githubusercontent.com/67706402/210945520-ae9b6fff-244b-4e4c-a8dd-9815d29c66a4.png">

**Comment by kewbish** [comment]
The hosted site seems to have gone down just recently as per [this issue](https://github.com/niccokunzmann/open-web-calendar/issues/139). Let's give it a day or two to see if it comes back up, but otherwise I can look into migrating to another service.

**Comment by kewbish** [comment]
The service is back up - closing!

**Comment by shubhbhalla** [comment]
Thank you @kewbish !
