### ISSUE TITLE
TCF Q&A Spotlight

### ISSUE THREAD

**Issue by tommysteryy** [ubccsss/ubccsss.org#345]
There's **two Q&A events** happening during the career fair that invites impressive people that hopefully gets more attendance for the TCF, and provides good ambient noise. I want students to know about it. @shmaiii and are co-leading these events, and she can send over more info in this thread once we have them.

But essentially I am thinking another "block" (right below "Companies Attending", and right above "Location + Event Map") that is split vertically in half, each half having a summary about one event, it's topic, and it's time. Then, each event will have it's own sub-page, where speaker info and content of the event is shared with more depth.

What do you think @kewbish? Could you draft up a block for us?

We won't have finalized info about the events speakers until **Sunday, January 15th**, so as long as this page is live on **Monday, January 16th**, we should be good. Let me know what you think!

**Comment by kewbish** [comment]
Yes, that's definitely doable - I'll draft up something soon.

Would we want the event summaries on the [main page event feed](https://ubccsss.org) as well? (Here ↓)
![image](https://user-images.githubusercontent.com/45278276/211215353-99b45bbc-9916-4cb6-b42d-25e0b58dd5ca.png)

If we do, we can create event pages on the 'normal' CSSS page and link to them through the summary blocks on the main TCF page.

Alternatively, if we want these Q&A events to be under the TCF page explicitly, I can do that too!

**Comment by tommysteryy** [comment]
Whichever one is easier! I guess there's no harm in having event pages as a "normal" CSSS event anyway, right? What is the downside of having them as "normal" CSSS events?

**Comment by kewbish** [comment]
It'd be easier to have them as 'normal' CSSS events. As a plus, they would show up in the event calendar at the bottom of the page as well.

The downside would be that the rest of the site would have the normal CSSS header (i.e. not the picture background with the blue overlay) and footer. 

I'll see if I can figure out how to add the TCF-style header and footer to the event pages though!

**Comment by shmaiii** [comment]
:)))) I think you can do it whatever way suits you best. Normal CSSS seems fine.

**Comment by kewbish** [comment]
How does something like this look?

![image](https://user-images.githubusercontent.com/45278276/211597776-fabb2bf3-b6a7-45b4-95a1-a9920c6e0f95.png)

**Comment by shmaiii** [comment]
it looks good to me! I can send you the description and details and stuff once I have all the speakers confirmed!

**Comment by tommysteryy** [comment]
Yea! It looks great. Please make the graphics if they need them, and put them up for now even if it’s just an event title + confirmed speaker names. Eventually, I think I am hoping that there are more details about the event and the speakers, but we can worry about that this weekend. From: Xuan Mai LuongSent: January 10, 2023 8:25 PMTo: ubccsss/ubccsss.orgCc: Tommy Xu; AuthorSubject: Re: [ubccsss/ubccsss.org] TCF Q&A Spotlight (Issue #345) it looks good to me! I can send you the description and details and stuff once I have all the speakers confirmed!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
