### ISSUE TITLE
TCF Employers Package

### ISSUE THREAD

**Issue by tommysteryy** [ubccsss/ubccsss.org#353]
On the **day of the event**, we will be giving employers a bunch of info:
- Venue map
- Important contact info
- Wifi passwords
- [...]

I was hoping to save the amount of paper we need to provide them with by giving them **a single qr-code** that leads them somewhere with all the information. I would have done a Google Doc, but I know some companies don't allow opening foreign google docs. Hence, I turn to the ubccsss website. What do you suggest? Make a repo for them? Is there a way for there to be a page on the `ubccsss.org` website with just a bunch of files?

**Comment by tommysteryy** [comment]
This would need to be up on the website and `url` ready by latest **Wednesday January 18th**. Of course, we would make the documents, but the location for it needs to be there too!

**Comment by kewbish** [comment]
Yes, this can be done for sure! We can make a page under `/tcf/employers` or something similar and we can host all the files statically on the site too.

One note is that there isn't any easy way to make the page password protected or gate access to just employers (i.e. if a student decides to snoop around this repo they can access the files.) The URL itself can be made more private if we add a small hash to the end of the URL, but let me know if this is necessary.

**Comment by tommysteryy** [comment]
That’s perfect! We don’t need any encryption cause I think these documents are all pretty much public knowledge. What do you need from me?

**Comment by kewbish** [comment]
I'll just need all the day-of information you'd like to host! (Or if not all of it, at least a couple documents to use as placeholders.)

**Comment by tommysteryy** [comment]
For sure. I will send them to you as soon as I can. For now, could you just help us make a couple of fake placeholders, if you need that? If the format matters, it'll be pdfs. 
If this page needs to be up and available by **January 19, 2023**, when do you need the documents by?

**Comment by kewbish** [comment]
Will do! I'd need the documents ideally by the morning of the day before (morning of the 18th), but anytime before the evening of the 18th works.
