### ISSUE TITLE
Fix prettier action

### ISSUE THREAD

**Issue by AnimeAllstar** [ubccsss/ubccsss.org#356]
https://github.com/ubccsss/ubccsss.org/pull/355

**Comment by AnimeAllstar** [comment]
The Prettier Action currently fails due to `master` being a protected branch.

https://github.com/ubccsss/ubccsss.org/actions/runs/3952733764/jobs/6768167670

**Comment by kewbish** [comment]
Thanks for letting me know, will take a look later on.
