### ISSUE TITLE
Tutoring info hasn't been put up

### ISSUE THREAD

**Issue by g-whiz** [ubccsss/ubccsss.org#493]
Hi,

I submitted a request to be listed as a tutor on the CSSS page about a week and a half ago. It seems as though it has not been added to the Tutor page yet.

Is there a problem with my request?

For reference, the email listed is "cpsc (dot) tutor (dot) george (at) gmail (dot) com". 

Thank you in advance for your help.

George

**Comment by kewbish** [comment]
Hello there! I don't see your application in our form responses.

Could you try again with [this link](https://docs.google.com/forms/d/e/1FAIpQLSfoGnxuuFfLuef7g4t9ZXPmUZ6d4DYx2Ij_BAicKss0Q0SlhA/viewform)?

**Comment by g-whiz** [comment]
Just resubmitted. Thanks for getting back about this!
