### ISSUE TITLE
Add Dark Mode on the website

### ISSUE THREAD

**Issue by justindhillon** [ubccsss/ubccsss.org#500]
The website hurts my eyes. I want to add a dark mode to the website. I am making this issue so I will know if my work will be merged. I will put the slider on the header bar.

![image](https://github.com/ubccsss/ubccsss.org/assets/145078271/1325c59a-acc4-437d-9a91-4f57d97ffa64)

**Comment by kewbish** [comment]
Hi there — your work here is welcome, but we can't guarantee that it will be reviewed or merged in a timely manner, especially if it requires significant refactoring.

(Also, I think a toggle button rather than a slider would work better.)

**Comment by justindhillon** [comment]
I am the greatest developer of all time. I just implemented the dark mode feature. You can see the pull request here #507

In return, I expect a 12 figure salary and a hug.
