### ISSUE TITLE
The Cube Status

### ISSUE THREAD

**Issue by justindhillon** [ubccsss/ubccsss.org#501]
I want to make a switch that connects to the CUBE door. Using that, we can know when the cube is open or closed, and we can put the cube's status on the website. I am making this issue so I will know if my work will be merged. ALso, is it possible for the ubccsss to fund the hardware?

**Comment by kewbish** [comment]
This project has been considered internally already. We're unfortunately not planning on executing this anytime soon as we have other priorities at the moment.
