### ISSUE TITLE
make a robots.txt file

### ISSUE THREAD

**Issue by wgervasio** [ubccsss/ubccsss.org#571]
I assume the TCF details were most likely scraped and that is how i started getting anonymous emails from people interested in the event and also from some external platform asking me to create an account. Would be good anyways to ensure stuff like GPT doesn't train on our website content unless we allow it.

**Comment by wgervasio** [comment]
Sample robots.txt from youtube.com


`# robots.txt file for YouTube
# Created in the distant future (the year 2000) after
# the robotic uprising of the mid 90's which wiped out all humans.

User-agent: Mediapartners-Google*
Disallow:

User-agent: *
Disallow: /comment
Disallow: /feeds/videos.xml
Disallow: /get_video
Disallow: /get_video_info
Disallow: /get_midroll_info
Disallow: /live_chat
Disallow: /login
Disallow: /qr
Disallow: /results
Disallow: /signup
Disallow: /t/terms
Disallow: /timedtext_video
Disallow: /verify_age
Disallow: /watch_ajax
Disallow: /watch_fragments_ajax
Disallow: /watch_popup
Disallow: /watch_queue_ajax

Sitemap: https://www.youtube.com/sitemaps/sitemap.xml
Sitemap: https://www.youtube.com/product/sitemap.xml
`

**Comment by RamitKataria** [comment]
As for the anonymous email issue, I don't know if these services would respect robots.txt. Cloudflare has a bot detection and email obfuscation product that we could use if we could use if we either switch to using Cloudflare Pages for deployment (would require refactoring our redirects), or use their proxy which would make things slightly inefficient (since it would be a CDN on top of a CDN).

robots.txt would definitely help though if we want to stop GPT training on our website.

**Comment by RamitKataria** [comment]
The Verge blocks GPT training and here's what theirs looks like:

```
User-agent: Googlebot-News
Disallow: /admin
Disallow: /newfanshot
Disallow: /users/*/replies
Disallow: /users/*/comments
Disallow: /search
Disallow: /account
Disallow: /login
Disallow: /chorus_auth
Disallow: /sso
Disallow: /ad
Disallow: /sponsored

User-agent: GPTBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: *
Disallow: /admin
Disallow: /newfanshot
Disallow: /users/*/replies
Disallow: /users/*/comments
Disallow: /search
Disallow: /account
Disallow: /login
Disallow: /chorus_auth
Disallow: /sso

Sitemap: https://www.theverge.com/sitemaps
Sitemap: https://www.theverge.com/sitemaps/authors
Sitemap: https://www.theverge.com/sitemaps/groups
Sitemap: https://www.theverge.com/sitemaps/videos

Sitemap: https://www.theverge.com/sitemaps/google_news
```

**Comment by wgervasio** [comment]
Very true with respect to people caring about the robots.txt . Anyhow verge looks like a good source to model off of

**Comment by kewbish** [comment]
I was thinking we should consider switching to Cloudflare Pages for deploys, as it's a little complicated having to manage emails and deploys via two separate platforms. Cloudflare Pages supports PR deploy previews, and +1 on email obfuscation.

Here, what should we disallow scraping for? I think it's good to still get our event / TCF pages indexed by Google, so maybe we can allow everything for Google and disallow everything for GPT / other user agents?

**Comment by RamitKataria** [comment]
@wgervasio For employer-exclusive material, we should probably look into a better solution (so that they're only accessible to employers) than robots.txt since it won't cover all the agents and it's just a polite request anyway.

**Comment by wgervasio** [comment]
Yeah I agree, most likely some light auth based method @RamitKataria
