### ISSUE TITLE
Change hourly rate

### ISSUE THREAD

**Issue by hawklu212** [ubccsss/ubccsss.org#622]
Hi this is Hawk, would it be possible to change my hourly rate to $50/hour , thank you

email:hawklu212@hotmail.com

**Comment by armanmoztar** [comment]
Hi, I can get this sorted for you.

**Comment by armanmoztar** [comment]
> Hi this is Hawk, would it be possible to change my hourly rate to $50/hour , thank you
> 
> email:[hawklu212@hotmail.com](mailto:hawklu212@hotmail.com)

Hi, I can get this sorted for you.

**Comment by hawklu212** [comment]
Thank you! Don’t see it changed yet though
