### ISSUE TITLE
KPMG logo is not loading

### ISSUE THREAD

**Issue by wgervasio** [ubccsss/ubccsss.org#684]
![image](https://github.com/user-attachments/assets/b4f5f2ea-efa4-4d73-982b-ce87a588f58b)

https://ubccsss.org/tcf/kpmg/

**Comment by wgervasio** [comment]
cc @kewbish

**Comment by kewbish** [comment]
Thanks for bringing this up! This is as intended as KPMG hasn't given us permission to use their logo yet :pray:

**Comment by wgervasio** [comment]
gotcha 👌 , things are looking great!
