### ISSUE TITLE
Update information to current year

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#72]
Review and make sure the following items are up to date: 
(Please comment below if there are things on the website that are not up to date)

- [x] Meeting minutes link (https://ubccsss.org/about/minutes/)
- [x] Announcement mailing list (https://ubccsss.org/contact/email-newsletter/)
- [x] Suggestion box (https://ubccsss.org/contact/email-newsletter/)
- [x] Volunteer page (https://ubccsss.org/volunteer/)
- [ ] Officer and committee links (https://ubccsss.org/about/team/misc/)
- [ ] Cube services/menu (https://ubccsss.org/cube/)
- [x] Coffee chat page (https://ubccsss.org/services/coffeechat/)
- [x] TCF Link (https://ubccsss.org/services/    https://ubctcf.com/)   In fact it leads to a random ad website?!

**Comment by kewbish** [comment]
Small things I found as well:
 - Footer still reads © 2019-2020.
 - The [Food Price List](https://ubccsss.org/cube/menu/) has a reference to [https://ubccsss.org/club/prices](https://ubccsss.org/club/prices), which redirects back to the original page.

**Comment by AnimeAllstar** [comment]
I've replaced the bullet points with a checklist, could y'all mark them if they're done?
