### ISSUE TITLE
Add professional headshot event

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#74]
See https://fb.me/e/1s27ibTKK

**Comment by aserputov** [comment]
Hey, I would like to work on this, can you please assign me?

**Comment by eqfy** [comment]
Hi @aserputov , thanks for your interest and feel free to submit a pull request! 

We actually wanted to have a new team member work on this update so that they can get familiar with the codebase. Nevertheless, we are open to contributions from the community :)

**Comment by aserputov** [comment]
@eqfy no problems at all, thank you for your reply. I will leave this issue till tomorrow; if it remains open, I will work on it. Sounds good?
