### ISSUE TITLE
Computer Science Clubs Page

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#94]
Create a new page featuring all the student clubs affiliated with UBC computer science. For each of the clubs, have their logos and the links to their websites.

Format similar to services page

UBC CTF
ACM
WICS
Queer Coded
NW Plus
UBC Game Dev
Please comment other clubs

**Comment by shubhbhalla** [comment]
Bizhacks

https://www.bizhacks.ca/

**Comment by AnimeAllstar** [comment]
Add a section for engineering design teams that offer cs opportunities; agrobot, rocket, etc.
